# Generated by Django 3.2.25 on 2026-03-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_tablecolumnconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sub_population', models.CharField(blank=True, max_length=100, null=True)),
                ('seq_data', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accession',
                'ordering': ['accession'],
            },
        ),
        migrations.DeleteModel(
            name='TableColumnConfig',
        ),
    ]
