# Generated by Django 3.2.25 on 2026-03-20 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20260320_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomefile',
            name='accession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.accession', verbose_name='Accession'),
        ),
    ]
