# Generated by Django 3.2.20 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_accession_country_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomefile',
            name='category',
            field=models.CharField(
                choices=[
                    ('variableBlocks', 'Variable Blocks'),
                    ('genome', 'Genome'),
                    ('transcriptome.all', 'Transcriptome-All'),
                    ('transcriptome.root', 'Transcriptome-Root'),
                    ('transcriptome.stem', 'Transcriptome-Stem'),
                    ('transcriptome.leaf', 'Transcriptome-Leaf'),
                    ('transcriptome.panicles', 'Transcriptome-Panicles'),
                    ('transcriptome.shoot', 'Transcriptome-Shoot'),
                    ('miRNA', 'miRNA'),
                    ('tRNA', 'tRNA'),
                    ('rRNA', 'rRNA'),
                    ('codon', 'Codon'),
                    ('centromere', 'Centromere'),
                    ('TEs', 'TEs'),
                    ('annotation', 'Annotation'),
                    ('coreBlocks', 'Core Blocks'),
                    ('other', 'Other'),
                ],
                max_length=50,
                verbose_name='File Category'
            ),
        ),
    ]
