# Generated by Django 3.2.9 on 2026-06-02 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_assembly_annotation_display_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('md5', models.CharField(blank=True, max_length=64, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'data_file',
                'ordering': ['file_code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['project_code'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chinese_name', models.CharField(blank=True, max_length=255, null=True)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonomy_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'species',
                'ordering': ['species_code'],
            },
        ),
        migrations.AddField(
            model_name='filetype',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filetype',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='filetype',
            name='format',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sample_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tissue', models.CharField(blank=True, max_length=100, null=True)),
                ('treatment', models.CharField(blank=True, max_length=255, null=True)),
                ('replicate', models.CharField(blank=True, max_length=100, null=True)),
                ('data_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='files.accession')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='files.species')),
            ],
            options={
                'db_table': 'sample',
                'ordering': ['sample_code'],
            },
        ),
        migrations.CreateModel(
            name='FileRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_type', models.CharField(choices=[('accession', 'Accession'), ('assembly', 'Assembly'), ('annotation', 'Annotation'), ('dataset', 'Dataset'), ('sample', 'Sample'), ('expression_matrix', 'Expression matrix'), ('variant_set', 'Variant set'), ('population_analysis', 'Population analysis'), ('other', 'Other')], max_length=50)),
                ('related_id', models.CharField(max_length=100)),
                ('related_code', models.CharField(blank=True, max_length=255, null=True)),
                ('file_role', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='files.datafile')),
            ],
            options={
                'db_table': 'file_relation',
                'ordering': ['related_type', 'related_id', 'file_role', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('dataset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset_type', models.CharField(choices=[('genome', 'Genome'), ('annotation', 'Annotation'), ('transcriptome', 'Transcriptome'), ('population_genetics', 'Population genetics'), ('variant', 'Variant'), ('phenotype', 'Phenotype'), ('other', 'Other')], default='other', max_length=50)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('lab_internal', 'Lab internal'), ('public', 'Public')], default='private', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('released', 'Released'), ('archived', 'Archived')], default='draft', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='files.project')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='files.species')),
            ],
            options={
                'db_table': 'dataset',
                'ordering': ['dataset_code'],
            },
        ),
        migrations.AddField(
            model_name='datafile',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_files', to='files.dataset'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='file_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_files', to='files.filetype'),
        ),
        migrations.AddField(
            model_name='accession',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessions', to='files.species'),
        ),
        migrations.AddIndex(
            model_name='filerelation',
            index=models.Index(fields=['related_type', 'related_id'], name='idx_fr_related'),
        ),
        migrations.AddIndex(
            model_name='filerelation',
            index=models.Index(fields=['related_type', 'related_id', 'file_role'], name='idx_fr_related_role'),
        ),
        migrations.AddIndex(
            model_name='filerelation',
            index=models.Index(fields=['file', 'related_type', 'related_id', 'file_role'], name='idx_fr_file_related_role'),
        ),
        migrations.AddConstraint(
            model_name='filerelation',
            constraint=models.UniqueConstraint(fields=('file', 'related_type', 'related_id', 'file_role'), name='uniq_file_relation_role'),
        ),
    ]
