# Generated by Django 3.2.9 on 2026-08-21 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_alter_dataset_dataset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='bioproject_accession',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='biosample_accession',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='experiment_accession',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AccessionExternalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_database', models.CharField(max_length=50)),
                ('external_study_accession', models.CharField(db_index=True, max_length=100)),
                ('biosample_accession', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('experiment_accession', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('run_accession', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('library_strategy', models.CharField(blank=True, max_length=100, null=True)),
                ('instrument_platform', models.CharField(blank=True, max_length=100, null=True)),
                ('instrument_model', models.CharField(blank=True, max_length=255, null=True)),
                ('fastq_url', models.TextField(blank=True, null=True)),
                ('fastq_md5', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='files.accession')),
            ],
            options={
                'db_table': 'accession_external_mapping',
                'ordering': ['external_study_accession', 'run_accession', 'id'],
            },
        ),
    ]
