import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = process.cwd()
const view = readFileSync(resolve(root, 'src/views/DataOverviewView.vue'), 'utf8')
const service = readFileSync(resolve(root, 'src/services/dataOverview.js'), 'utf8')
const stats = readFileSync(resolve(root, 'src/components/data-overview/DataOverviewStats.vue'), 'utf8')
const columns = readFileSync(resolve(root, 'src/components/data-overview/DataOverviewColumnSettings.vue'), 'utf8')
const drawer = readFileSync(resolve(root, 'src/components/data-overview/DataFileDetailDrawer.vue'), 'utf8')

assert.match(service, /\/files\/query\/data-overview\//, 'file list uses the file-level overview endpoint')
assert.match(service, /\/files\/data-files\/\$\{fileId\}\/detail\//, 'detail opens the selected DataFile')
assert.match(service, /\{ \.\.\.config, params \}/, 'overview requests accept cancellation and other request configuration')
assert.match(view, /data\.results \|\| \[\]/, 'page consumes the v2 results contract')
assert.doesNotMatch(view, /matrix_rows|detail_rows|data-overview-files/, 'old Accession matrix contract is removed')
assert.match(view, /draft\.category/)
assert.match(view, /draft\.species/)
assert.match(view, /draft\.accession/)
assert.match(view, /draft\.dataset/)
assert.match(view, /DEFAULT_COLUMNS = \['category', 'file_name', 'species_name', 'accession', 'file_type', 'file_size_display'\]/)
assert.match(view, /DataOverviewColumnSettings/)
assert.match(view, /openDetail\(row\.file_id\)/)
assert.match(view, /page_size: pageSize\.value/)
assert.match(view, /:value="20"/)
assert.match(view, /:value="50"/)
assert.match(view, /:value="100"/)
assert.match(stats, /assembly_count/)
assert.match(stats, /grid-template-columns:repeat\(5/)
assert.match(columns, /el-checkbox-group/)
assert.doesNotMatch(drawer, /file_path|复制文件路径|Copy Path/, 'the public drawer must not expose storage paths')
assert.match(drawer, /detail\.md5/)
assert.match(drawer, /detail\.download_url/)
assert.match(drawer, /copyMd5/, 'the detail drawer exposes a safe checksum copy action')
assert.match(drawer, /\$emit\('retry'\)/, 'the detail drawer can retry a failed request')
assert.match(drawer, /:aria-busy="loading"/, 'the detail drawer announces its loading state')
assert.match(view, /detailError/, 'the page keeps a recoverable detail error state')
assert.match(view, /@retry="loadDetail"/, 'the detail drawer retry action is wired to the API request')
assert.match(view, /<caption class="sr-only">/, 'the data table has an accessible caption')
assert.match(view, /:aria-busy="loading"/, 'the data table announces its loading state')
assert.match(view, /useRouter/, 'the page synchronizes restorable state through the router')
assert.match(view, /page_size/, 'page size is represented in URL state')
assert.match(view, /watch\(\(\) => route\.query/, 'browser history restores filters and pagination')
assert.match(view, /new AbortController\(\)/, 'superseded list and detail requests can be cancelled')
assert.match(view, /onBeforeUnmount/, 'in-flight requests are released when the page unmounts')
assert.doesNotMatch(view + service + drawer, /genome-files|legacy_genomefile|organism_fallback/)

console.log('data-overview file-level source checks passed')
