"""
Django settings for filemanager project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import platform

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-development-only-change-me',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# 网站URL设置
SITE_URL = 'https://riceome.hzau.edu.cn'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'files',
    'rest_framework',
    'corsheaders',
    'integrations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS设置
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:8085",
    "https://riceome.hzau.edu.cn",
]

# CORS和CSRF设置
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-client-id',
]

# CSRF设置
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:8085",
    "https://riceome.hzau.edu.cn",
]

ROOT_URLCONF = 'filemanager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'filemanager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('GENEDATA_DB_NAME', 'gene_manage'),
        'USER': os.environ.get('GENEDATA_DB_USER', 'root'),
        'PASSWORD': os.environ.get('GENEDATA_DB_PASSWORD', "PassWord123@"),
        'HOST': os.environ.get('GENEDATA_DB_HOST', 'localhost'),
        'PORT': os.environ.get('GENEDATA_DB_PORT', '3306'),
    }
}

# Ordered accession identifiers promoted on the portal homepage. Unknown values
# are ignored by the dashboard service, so deployments can manage this list
# without coupling it to migrations.
DASHBOARD_FEATURED_ACCESSIONS = tuple(
    value.strip()
    for value in os.environ.get('GENEDATA_FEATURED_ACCESSIONS', '').split(',')
    if value.strip()
)


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Media files (用户上传的文件)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Annotation source files are indexed offline. These caches only contain
# database-backed API payloads and are versioned by the source-file fingerprint.
ANNOTATION_OPTIONS_CACHE_SECONDS = 60 * 60
ANNOTATION_DATA_CACHE_SECONDS = 5 * 60
ANNOTATION_MAX_PAGE_SIZE = 10000

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 文件路径配置
# 根据操作系统选择不同的路径
if platform.system() == 'Windows':
    # Windows环境
    MANUAL_FILES_DIR = r'D:\gene_manage_system\gene_manage_system\manual_files'
else:
    # Linux环境
    MANUAL_FILES_DIR = '/home/labuser/rdcheng/gd/manual_files'

# 文件上传配置
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024 * 1024  # 10GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024 * 1024  # 10GB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000  # 增加字段数量限制

# CodonW工具配置
if platform.system() == 'Windows':
    # Windows环境下的CodonW程序路径
    CODONW_EXECUTABLE = r'D:\gene_manage_system\tools\codonw\codonw.exe'
else:
    # Linux环境下的CodonW程序路径
    # 优先使用conda环境中的codonw，如果不存在则使用系统路径
    import shutil
    conda_codonw = shutil.which('codonw')
    if conda_codonw:
        CODONW_EXECUTABLE = conda_codonw
    else:
        CODONW_EXECUTABLE = '/usr/local/bin/codonw'

# CodonW分析配置
CODONW_TIMEOUT = 1800  # 分析超时时间（秒，30分钟）
CODONW_MAX_FILE_SIZE = 10 * 1024 * 1024 * 1024  # 最大文件大小（10GB）
